// Svelte/to-do-app/src/components/ToDo.svelte
<script>
    let tasks = []
    let task = ''

    function addTask() {
        tasks = [...tasks, task]
    }
</script>

<ul>
    {#each tasks as task}
    <li>{task}</li>
    {/each}
</ul>

<div>
    <label for="task">Thing To Add:</label>
    <input type="text" name="task" id="task" bind:value="{task}">
</div>

<button title="Add task" on:click="{addTask}">Add</button>

// Angular/to-do-app/src/app/to-do/to-do.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-to-do',
  templateUrl: './to-do.component.html',
  styleUrls: ['./to-do.component.sass']
})
export class ToDoComponent implements OnInit {
  tasks: string[] = []

  constructor() { }

  ngOnInit(): void {
  }

  add(task: string): void {
    task = task.trim()

    if (!task) return;

    this.tasks.push(task)
  }
}

<ul>
    <li *ngFor="let task of tasks">{{task}}</li>
</ul>

<div>
    <label for="task">Thing To Add:</label>
    <input type="text" name="task" id="task" #task>

    <button title="Add task" (click)="add(task.value)">Add</button>
</div>
